useDotenv: true

service: openai-api-apps
frameworkVersion: "3"
provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: nodejs18.x

package:
  patterns:
    - "!**"
    - ".output/**"

functions:
  NuxtSsrEngine:
    handler: ".output/server/index.handler"
    url: true
    environment:
      DB_URL: ${env:DB_URL}
